#!/usr/bin/env python

import argparse
from datetime import datetime
from lib import lywsd02
import Cli

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
dispatch, choices, helptext = Cli.Commands.create(parser);
parser.add_argument('command', help=helptext, choices=choices)
parser.add_argument('mac', help='MAC address of LYWSD02 device', nargs='+')
args = parser.parse_args()

for mac in args.mac:
    try:
        client = lywsd02.Lywsd02Client(mac)
        dispatch[args.action](client)
    except Exception as e:
        print(e)

