#!/usr/bin/env python

import argparse
import sys
import traceback

from cli import Devices
from cli import Commands

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)

Devices.add_parser(parser)
devices = Devices.create()

Commands.add_parser(parser)
commands = Commands.create()

parser.add_argument('mac', help='MAC address of the device', nargs='+')

args = parser.parse_args()

for mac in args.mac:
    try:
        device = devices[args.device](mac)
        commands[args.command](device)
    except Exception as e:
        traceback.print_exception(*sys.exc_info())
        sys.exit(1)
