#!/bin/bash
pushd `dirname $BASH_SOURCE`
[ -d ./venv ] && source ./venv/bin/activate
./sensor lywsd02 send E7:2E:00:51:C0:95 # LYWSD02
./sensor lywsd03 send A4:C1:38:36:1B:73 # ATC_361B73
./sensor lywsd03 send A4:C1:38:B9:18:1F # ATC_B9181F
popd
