#!/bin/bash
pushd `dirname $BASH_SOURCE`
[ -d ./venv ] && source ./venv/bin/activate

./sensor lywsd02 send E7:2E:00:51:C0:95 # LYWSD02
./sensor lywsd02 sendh E7:2E:00:51:C0:95 # LYWSD02
#./sensor lywsd03 send A4:C1:38:36:1B:73 # ATC_361B73 - dead
#./sensor lywsd03 send A4:C1:38:B9:18:1F # ATC_B9181F - dead
./sensor lywsd03 send  A4:C1:38:43:61:0E # ATC_43610E - carol
./sensor lywsd03 sendh A4:C1:38:43:61:0E # ATC_43610E - carol
./sensor lywsd03 send  A4:C1:38:29:CA:D6 # ATC_29CAD6 - cold frame
./sensor lywsd03 sendh A4:C1:38:29:CA:D6 # ATC_29CAD6 - cold frame

rm -f weather.json
curl wttr.in/43.05,-87.98?format=j1 > weather.json
./sendWeather
rm -f weather.json

popd
